name: mimir-kgrag

x-weaviate: &weaviate
  image: semitechnologies/weaviate:stable-v1.28-bb97ca3
  environment:
    AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
    PERSISTENCE_DATA_PATH: /var/lib/weaviate
    QUERY_DEFAULTS_LIMIT: "25"
    DEFAULT_VECTORIZER_MODULE: "none"
    CLUSTER_HOSTNAME: node1
  networks:
    - kgrag_network

x-neo4j: &neo4j
  image: neo4j:latest
  restart: always
  networks:
    - kgrag_network

x-ollama: &ollama
  image: alpine/ollama:0.3.13
  networks:
    - kgrag_network

services:
  mimir-kgrag-ollama:
    <<: *ollama
    profiles: [ ollama ]
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11435:11434"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

  mimir-dev-kgrag-weaviate:
    <<: *weaviate
    profiles: [ dev ]
    ports:
      - "8083:8080"

  mimir-test-kgrag-weaviate:
    <<: *weaviate
    profiles: [ test ]
    ports:
      - "8084:8080"

  mimir-dev-kgrag-neo4j:
    <<: *neo4j
    profiles: [ dev ]
    environment:
      - NEO4J_AUTH=neo4j/test_password
    ports:
      - "7474:7474"
      - "7687:7687"

  mimir-test-kgrag-neo4j:
    <<: *neo4j
    profiles: [ test ]
    environment:
      - NEO4J_AUTH=neo4j/test_password
    ports:
      - "7475:7474"
      - "7688:7687"

  mimir-nermal:
    image: violabs/nermal:0.0.1
    ports:
      - "5001:5001"

networks:
  kgrag_network:
    driver: bridge
