spring:
  datasource:
    username: testuser
    password: testpassword
    url: jdbc:mysql://localhost:3306/simpletest
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect