app:
  seed-data:
    enabled: false
  vector:
    weaviate:
      scheme: ${WEAVIATE_SCHEME:http}
      host: ${WEAVIATE_HOST:localhost:8083}

spring:
  application:
    name: kg-rag
  ai:
    ollama:
      embedding:
        options:
          model: ${EMBEDDINGS_OLLAMA_MODEL:nomic-embed-text:latest}
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:test_password}

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    groups-order: asc
    doc-expansion: none  # Collapses all operations by default
    default-models-expand-depth: -1  # Hide schemas section by default
    disable-swagger-default-url: true
    tags-sorter: alpha
    syntax-highlight:
      activated: true
    try-it-out-enabled: true  # Enables "Try it out" feature
    display-request-duration: true  # Shows request execution time
    filter: true  # Adds a search box
  packages-to-scan: io.violabs.mimir.vector.weaviate  # Adjust this to your base package
  paths-to-match: /api/**  # Adjust this to your API paths pattern
  show-actuator: false  # Set to true if you want to document actuator endpoints
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  use-management-port: false
  writer-with-default-pretty-printer: true

server:
  port: ${PORT:8081}