app:
  seed-data:
    enabled: false
  vector:
    weaviate:
      host: ${WEAVIATE_HOST:localhost:8084}

spring:
  application:
    name: kg-rag
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11435}
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7688}