
spring.kafka:
  bootstrap-servers:
    - localhost:29092
    - localhost:39092
  producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  consumer.value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer