version: '3.8'

services:
  weviate:
    image: semitechnologies/weaviate:1.22.4
    ports:
      - "8083:8080"
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - QUERY_DEFAULTS_LIMIT=25
      - DEFAULT_VECTORIZER_MODULE=none
      - CLUSTER_HOSTNAME=node1

volumes:
  weviate_data: