spring:
  datasource:
    url: jdbc:sqlserver://localhost:8082;databaseName=simpletest
    username: sa
    password: Str0ngPassword!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect