spring:
  application.name: milvus
  ai:
    ollama:
      chat:
        enabled: true
        options:
          model: dolphin-mixtral:8x7b-v2.6
      embedding:
        options:
          model: dolphin-mixtral:8x7b-v2.6
      base-url: http://localhost:11434

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    groups-order: asc
server:
  port: 8081