name: 'ibm-mq'

x-ibm-mq: &ibm-mq
  image: ibm-mqadvanced-server-dev:9.4.4.0-arm64 # do not change this
  environment:
    LICENSE: accept
    MQ_QMGR_NAME: QM1
    MQ_APP_PASSWORD: passw0rd
    MQ_ADMIN_PASSWORD: passw0rd
  volumes:
    - qm1data:/mnt/mqm

services:
  dev-ibm-mq:
    <<: *ibm-mq
    profiles: [dev]
    ports:
      - "1414:1414"
      - "9443:9443"
      - "9157:9157"

  test-ibm-mq:
    <<: *ibm-mq
    profiles: [test]
    ports:
      - "1415:1414"
      - "9444:9443"
      - "9158:9157"

volumes:
  qm1data: