
app.topics:
  error:
    interval: 1000
    max-retry: 2
  gods:
    topic-name: god.topic
    partitions: 2
    replications: 1
  monsters:
    topic-name: monster.topic
    partitions: 2
    replications: 1

spring.kafka:
  bootstrap-servers:
    - localhost:29092
    - localhost:39092
  producer.value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  consumer.value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer