services:
  postgres: # https://hub.docker.com/_/postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    profiles: [dev]

  postgres-test:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    profiles: [test]