name: 'postgres'

x-postgres: &postgres
  image: postgres:latest
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_DB: postgres

services:
  dev-postgres:
    <<: *postgres
    profiles: [dev]
    ports:
      - "5432:5432"

  test-postgres:
    <<: *postgres
    profiles: [dev]
    ports:
      - "5432:5432"