name: 'graphql-async'

x-postgres: &postgres
  image: postgres:latest
  environment:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: password
    POSTGRES_DB: graphql

services:
  dev-postgres:
    <<: *postgres
    profiles: [dev]
    ports:
      - "5432:5432"

  test-postgres:
    <<: *postgres
    profiles: [test]
    ports:
      - "5432:5432"