name: 'mimir-database-mysql'

x-mysql: &mysql
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_DATABASE: simple
    MYSQL_USER: localuser
    MYSQL_PASSWORD: localpassword

services:
  dev-mysql:
    <<: *mysql
    profiles: [local, dev]
    ports:
      - "3306:3306"

  test-mysql:
    <<: *mysql
    profiles: [test]
    ports:
      - "3306:3306"