
app:
  vector:
    weaviate:
      scheme: ${WEAVIATE_SCHEME:http}
      host: ${WEAVIATE_HOST:localhost:8080}

spring:
  application.name: weaviate
  ai:
    ollama:
      chat:
        enabled: true
        options:
          model: ${CHAT_OLLAMA_MODEL:deepseek-r1:32b}
      embedding:
        options:
          model: ${EMBEDDINGS_OLLAMA_MODEL:nomic-embed-text:latest}
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    groups-order: asc
server:
  port: ${PORT:8081}